// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestingAkbas.Data;

namespace TestingAkbas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestingAkbas.Models.Fabric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("DomesticPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ExportPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FabricCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatternType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QualityClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QualityComposition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QualityGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QualityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RawFabricPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Fabrics");
                });
#pragma warning restore 612, 618
        }
    }
}
